### PR TITLE
Make the 8ball look fancy

### PR DESCRIPTION
**Pull request by treyhunner**
Very different approach to the one you took.

A triangle fades in and then fades out after a few seconds.

I think I like the shaking one better.

selection_464
selection_465

### CODE REVIEW

**Comment by sunnydatko** [comment]
I was considering a triangle design too.  I like what you've done.

**Comment by sunnydatko** [comment]
Do you think we can combine the two concepts?

**Comment by treyhunner** [comment]
Yes we probably could. I saw you used jQuery for the shake effect.  I used a lot of CSS for the things I did.

Did you want to introduce jQuery?

**Comment by sunnydatko** [comment]
I was torn on that too but didn't know how to duplicate the code in plain old Javascript.  We could try translating it to JS but the students will probably not be able to read it either way.  

I have a comment before the jquery script saying the code works past this point and to focus on the code above that line.  We could explain to the students what jquery is and that it creates the shaking effect, I think it would be cool for them to see the potential it offers without digging into it yet.

Any thoughts?

**Comment by sunnydatko** [comment]
Also we should get rid of the text box unless we are going to add validation to check that the user wrote something in it- which I don't want to do because we haven't covered validation yet.

**Comment by treyhunner** [comment]
I'm fine with adding jQuery.  A non-jQuery solution would also not be understandable by them and it would require a lot more lines of CSS (or JS) to do a custom shake.

I agree that we should git rid of the text box.

I will introduce CSS bugs in the code tomorrow morning.  I'm fine with using your 8 ball if you want since it would require less CSS.

**Pull request closed without merging**
